on:
  schedule:
    - cron: "0 0 * * 0" # At 00:00 on every Sunday.

  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# If you trigger a new workflow while the previous one is running,
# this will cancel the previous one.
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true


jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      # Use matrix strategy to run the tests on multiple Py versions on multiple OSs.
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.9", "3.10"]
        include:
        - os: ubuntu-latest
          path: ~/.cache/pip
        - os: macos-latest
          path: ~/Library/Caches/pip

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/cache@v3
        with:
          path: ${{ matrix.path }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}-${{ hashFiles('**/requirements-dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install the Dependencies
        run: |
          echo "Installing the dependencies..."
          python -m pip install -r requirements.txt
          python -m pip install -r requirements-dev.txt

      - name: Check Linter
        run: |
          echo "Checking linter formatting..."
          make lint-check

      - name: Run Tests
        run: |
          echo "Running the tests..."
          export PYTHONWARNINGS="ignore" && pytest -v -s -k 'not integration'
